### ISSUE TITLE
aws-api-gateway-graal does not build

### ISSUE THREAD

**Issue by itsdrew** [micronaut-projects/micronaut-profiles#151] opened 2019-04-26 11:04 UTC
| Micronaut Version: 1.1.0
| JVM Version: 1.8.0_201

```
mn create-app graaltest --features aws-api-gateway-graal
cd graaltest
./docker-build.sh
```

Tail of logs leading up to and including error:

```
graalvm-ce-1.0.0-rc15/jre/lib/graal/graal-replacements-processor.jar
graalvm-ce-1.0.0-rc15/jre/lib/graal/graal-compiler-match-processor.jar
graalvm-ce-1.0.0-rc15/jre/tools/regex/tregex.jar
graalvm-ce-1.0.0-rc15/jre/tools/regex/native-image.properties
graalvm-ce-1.0.0-rc15/jre/lib/jvmci/parentClassLoader.classpath
graalvm-ce-1.0.0-rc15/jre/bin/polyglot
graalvm-ce-1.0.0-rc15/include/trufflenfi.h
Removing intermediate container 62b9219c4900
 ---> 45d6d920364c
Step 12/22 : RUN rm -rf /tmp/*
 ---> Running in 8e3c24f4ed56
Removing intermediate container 8e3c24f4ed56
 ---> 2f5c8c726c26
Step 13/22 : CMD ["/usr/lib/graalvm/bin/native-image"]
 ---> Running in 479326469baf
Removing intermediate container 479326469baf
 ---> a5c8cf91304d
Step 14/22 : FROM graalvm
 ---> a5c8cf91304d
Step 15/22 : COPY --from=builder /home/application/ /home/application/
 ---> 00c70ba9a827
Step 16/22 : WORKDIR /home/application
 ---> Running in 5a9b6e515736
Removing intermediate container 5a9b6e515736
 ---> efbf8bf6361d
Step 17/22 : RUN /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/graaltest-*.jar
 ---> Running in ad8b171cf171
[server:7]    classlist:   4,236.68 ms
[server:7]        (cap):     853.75 ms
[server:7]        setup:   1,902.75 ms
Warning: class initialization of class com.amazonaws.serverless.proxy.internal.LambdaContainerHandler failed with exception java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/afterburner/AfterburnerModule. This class will be initialized at run time because either option --report-unsupported-elements-at-runtime or option --allow-incomplete-classpath is used for image building. Use the option --delay-class-initialization-to-runtime=com.amazonaws.serverless.proxy.internal.LambdaContainerHandler to explicitly request delayed initialization of this class.
[server:7]     analysis: 123,205.03 ms
Error: Error encountered while parsing io.micronaut.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(io.micronaut.caffeine.cache.Caffeine, io.micronaut.caffeine.cache.CacheLoader, boolean) 
Parsing context:
	parsing io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3029)
	parsing io.micronaut.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3025)
	parsing io.micronaut.caffeine.cache.Caffeine.build(Caffeine.java:847)
	parsing io.micronaut.cache.DefaultSyncCache.buildCache(DefaultSyncCache.java:189)
	parsing io.micronaut.cache.DefaultSyncCache.<init>(DefaultSyncCache.java:85)
	parsing io.micronaut.cache.DefaultSyncCache.<init>(DefaultSyncCache.java:68)
	parsing io.micronaut.cache.$DefaultSyncCacheDefinition.build(Unknown Source)
	parsing io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	parsing io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2475)
	parsing io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2375)
	parsing io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:587)
	parsing io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1022)
	parsing io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:214)
	parsing io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	parsing io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:180)
	parsing io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:103)
	parsing io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.getAwsProxyHandler(MicronautLambdaContainerHandler.java:132)
	parsing io.micronaut.function.aws.runtime.MicronautLambdaRuntime.startRuntimeApiEventLoop(MicronautLambdaRuntime.java:110)
	parsing io.micronaut.function.aws.runtime.MicronautLambdaRuntime.main(MicronautLambdaRuntime.java:75)
	parsing com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:153)
	parsing com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
The command '/bin/sh -c /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/graaltest-*.jar' returned a non-zero code: 1
```

**Comment by ZacharyKlein** [comment] 2019-06-27 02:14
Cannot reproduce with 1.2.0.RC1 - closing for now, please re-open if this issue continues.

**Closed by ZacharyKlein** 2019-06-27 02:14 UTC
