### ISSUE TITLE
Creating a Java app with Spock puts the Groovy dependency into compile scope

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-profiles#62] opened 2018-08-10 07:03 UTC
Running

```
 mn create-app fresh-spock --features spock --build maven
```

Results in a dependency like:

```xml
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy</artifactId>
    </dependency>
```

It should be

```xml
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy</artifactId>
      <scope>test</scope>
    </dependency>
```

Since Groovy is only needed for testing

**Comment by ZacharyKlein** [comment] 2018-08-18 06:41
I'm not sure we can support this with the way the CLI currently works. The problem is that if I put the dependency into test scope for the `spock` feature, it will be included in both Java and Groovy projects. That breaks Groovy projects (because of the duplicate Groovy dependencies. 

cc @jameskleeh  thoughts?

**Comment by jameskleeh** [comment] 2018-08-18 06:43
@ZacharyKlein Seems like this and others will need the overhaul of the CLI to a more code based approach

**Comment by ZacharyKlein** [comment] 2018-08-18 06:44
Agreed, perhaps we should add a label for such features. I don't want to lose track of this but I don't think it can be done in time for the next milestone.

**Comment by benrhine** [comment] 2019-11-21 15:01
Closing as this is no longer the case. Only references to groovy in a java/maven app are in the test scope

```
<dependency>
      <groupId>org.spockframework</groupId>
      <artifactId>spock-core</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.micronaut</groupId>
      <artifactId>micronaut-inject-groovy</artifactId>
      <scope>test</scope>
</dependency>
```

**Closed by benrhine** 2019-11-21 15:01 UTC
Labels: needs cli refactor
