### ISSUE TITLE
Default active features for a certain profile?

### ISSUE THREAD

**Issue by aadrian** [micronaut-projects/micronaut-profiles#181] opened 2019-08-28 09:06 UTC
It would be really helpful if it would be visible when creating a new project with a specific profile, what features are already "active" (default on), without the need to specify them.

Thank you.

**Comment by benrhine** [comment] 2019-12-04 19:49
I am closing this as it is a duplicate of core issue #1774. Please watch the alternate issue for updates in the near future.

**Closed by benrhine** 2019-12-04 19:49 UTC
Labels: duplicate
